package com.bridgelabz.cricketanalyser;

public enum SortedField {
    BATTINGAVG, MAXIMUMHIT, STRIKERATE6S4S, AVGWITHSTRIKE, MAXRUNS, MAXRUNSWITHAVG, STRIKINGRATE,
    ECONOMYRATE, STRIKERATE4W5W, BOWLINGAVGWITHSTRIKERATE, MAXWKTSWITHBOWLINGAVG, BOWLINGAVGWITHBATTINGAVG, ALLROUNDERAVG, ALLROUNDER, BOWLINGAVG
}
